import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";

test("reporting-service is registered as a target Spring Boot service with PostgreSQL backing", async () => {
  const settings = await readFile("settings.gradle.kts", "utf8");
  const rootPackage = JSON.parse(await readFile("package.json", "utf8"));
  const application = await readFile("services/reporting-service/src/main/resources/application.yml", "utf8");
  const build = await readFile("services/reporting-service/build.gradle.kts", "utf8");
  const dockerfile = await readFile("infra/docker-compose/reporting-service.Dockerfile", "utf8");
  const compose = await readFile("docker-compose.yml", "utf8");
  const prometheus = await readFile("infra/observability/prometheus/prometheus.yml", "utf8");
  const migration = await readFile("services/reporting-service/src/main/resources/db/migration/V001__reporting_service_foundation.sql", "utf8");
  const renderingMigration = await readFile("services/reporting-service/src/main/resources/db/migration/V002__report_artifact_rendering.sql", "utf8");
  const retentionMigration = await readFile("services/reporting-service/src/main/resources/db/migration/V003__report_artifact_retention_lifecycle.sql", "utf8");
  const keycloakServiceTokenSmoke = await readFile("scripts/run-reporting-keycloak-service-token-smoke.sh", "utf8");

  assert.match(settings, /include\(":services:reporting-service"\)/);
  assert.equal(rootPackage.scripts["test:reporting-service:unit"], "scripts/run-core-banking-tests.sh :services:reporting-service:test");
  assert.equal(rootPackage.scripts["test:reporting-service:integration"], "scripts/run-core-banking-tests.sh :services:reporting-service:integrationTest");
  assert.equal(rootPackage.scripts["test:reporting-service:keycloak-service-token"], "bash scripts/run-reporting-keycloak-service-token-smoke.sh");
  assert.match(build, /org\.springframework\.boot/);
  assert.match(build, /flyway-database-postgresql/);
  assert.match(build, /org\.testcontainers:postgresql/);
  assert.match(application, /baseline-on-migrate: \$\{BANKING_LAB_REPORTING_FLYWAY_BASELINE_ON_MIGRATE:true\}/);
  assert.match(application, /baseline-version: \$\{BANKING_LAB_REPORTING_FLYWAY_BASELINE_VERSION:0\}/);
  assert.match(dockerfile, /reporting-service-\*-migration\.jar/);
  assert.match(compose, /reporting-service:/);
  assert.match(compose, /SPRING_FLYWAY_TABLE: reporting_flyway_schema_history/);
  assert.match(compose, /BANKING_LAB_REPORTING_DATABASE_URL: jdbc:postgresql:\/\/postgres:5432\/banking_lab/);
  assert.match(compose, /BANKING_LAB_SECURITY_AUDIENCE: "\$\{BANKING_LAB_REPORTING_SECURITY_AUDIENCE:-reporting-service-api\}"/);
  assert.match(prometheus, /job_name: reporting-service/);
  assert.match(prometheus, /reporting-service:8090/);
  assert.match(migration, /CREATE TABLE report_definitions/);
  assert.match(migration, /CREATE TABLE report_artifacts/);
  assert.match(migration, /CREATE TABLE reporting_access_audit_events/);
  assert.match(migration, /UNIQUE \(requested_by, idempotency_key\)/);
  assert.match(migration, /'AUDIT_SUMMARY'/);
  assert.match(migration, /'EVIDENCE_COVERAGE'/);
  assert.match(renderingMigration, /artifact_content JSONB NOT NULL/);
  assert.match(renderingMigration, /content_sha256 TEXT NOT NULL/);
  assert.match(renderingMigration, /retention_policy TEXT NOT NULL/);
  assert.match(renderingMigration, /chk_report_artifacts_synthetic_rendered_content/);
  assert.match(retentionMigration, /EXPIRED/);
  assert.match(retentionMigration, /SYNTHETIC_RETENTION_EXPIRED/);
  assert.match(retentionMigration, /idx_report_artifacts_retention_until/);
  assert.match(keycloakServiceTokenSmoke, /grant_type=client_credentials/);
  assert.match(keycloakServiceTokenSmoke, /client_id=reporting-service-api/);
  assert.match(keycloakServiceTokenSmoke, /BANKING_LAB_SECURITY_SIMULATOR_TOKENS_ENABLED=false/);
  assert.match(keycloakServiceTokenSmoke, /REPORTING_ANALYST/);
  assert.match(keycloakServiceTokenSmoke, /reporting-service-api audience/);
  assert.match(keycloakServiceTokenSmoke, /\/api\/reports\/catalog/);
  assert.match(keycloakServiceTokenSmoke, /\/api\/reports\/artifacts/);
  assert.match(keycloakServiceTokenSmoke, /\/api\/reports\/artifacts\/\$\{ARTIFACT_ID\}\/export/);
  assert.match(keycloakServiceTokenSmoke, /\/api\/reports\/retention\/sweeps/);
  assert.match(keycloakServiceTokenSmoke, /expiredCount/);
  assert.match(keycloakServiceTokenSmoke, /downloadSimulationOnly/);
  assert.match(keycloakServiceTokenSmoke, /maskedByDefault/);
});

test("reporting-service API enforces synthetic reporting controls in source and tests", async () => {
  const service = await readFile("services/reporting-service/src/main/kotlin/lab/banking/reporting/domain/ReportingService.kt", "utf8");
  const models = await readFile("services/reporting-service/src/main/kotlin/lab/banking/reporting/domain/ReportingModels.kt", "utf8");
  const filter = await readFile("services/reporting-service/src/main/kotlin/lab/banking/reporting/security/ReportingAuthorizationFilter.kt", "utf8");
  const errorContract = await readFile("services/reporting-service/src/main/kotlin/lab/banking/reporting/api/ReportingApiError.kt", "utf8");
  const integrationTest = await readFile("services/reporting-service/src/integrationTest/kotlin/lab/banking/reporting/ReportingServiceIntegrationTest.kt", "utf8");

  assert.match(service, /Isolation\.SERIALIZABLE/);
  assert.match(service, /requireReason/);
  assert.match(service, /existingArtifact/);
  assert.match(service, /renderArtifactContent/);
  assert.match(service, /exportArtifact/);
  assert.match(service, /runRetentionSweep/);
  assert.match(service, /REPORT_ARTIFACT_EXPORTED/);
  assert.match(service, /REPORT_RETENTION_SWEEP_RUN/);
  assert.match(service, /sha256/);
  assert.match(service, /REPORT_GENERATED/);
  assert.match(models, /REPORTING_POLICY_REASON_REQUIRED/);
  assert.match(models, /ReportArtifactExportResponse/);
  assert.match(models, /ReportRetentionSweepResponse/);
  assert.match(models, /artifactContent/);
  assert.match(models, /contentSha256/);
  assert.match(models, /maskedByDefault/);
  assert.match(filter, /REPORTING_RBAC_ROUTE_POLICY/);
  assert.match(filter, /AUDITOR/);
  assert.match(filter, /COMPLIANCE_MANAGER/);
  assert.match(errorContract, /supporting\/03-reporting-service\.md/);
  assert.match(errorContract, /syntheticOnly: Boolean = true/);
  assert.match(integrationTest, /isUnauthorized/);
  assert.match(integrationTest, /isForbidden/);
  assert.match(integrationTest, /REPORTING_POLICY_REASON_REQUIRED/);
  assert.match(integrationTest, /RPT-IT-001/);
  assert.match(integrationTest, /contentSha256/);
  assert.match(integrationTest, /\/export/);
  assert.match(integrationTest, /retention\/sweeps/);
  assert.match(integrationTest, /EXPIRED/);
  assert.match(integrationTest, /downloadSimulationOnly/);
  assert.match(integrationTest, /SYNTHETIC_7Y/);
  assert.match(integrationTest, /reporting_access_audit_events/);
});
