global:
  scrape_interval: 15s

scrape_configs:
  - job_name: core-banking
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - core-banking:8081
          - core-banking-temporal-worker:8081
          - core-banking-outbox-worker:8081
  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - notification-service:8089
          - notification-event-consumer:8089
  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - payment-service:8088
          - payment-outbox-worker:8088
          - payment-domain-event-publisher:8088
  - job_name: reporting-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - reporting-service:8090
          - reporting-domain-event-publisher:8090
  - job_name: redpanda
    static_configs:
      - targets:
          - redpanda:9644
