apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-lab-config
  namespace: banking-lab
  labels:
    app.kubernetes.io/part-of: banking-lab
data:
  BANKING_LAB_SYNTHETIC_ONLY: "true"
  BANKING_LAB_TRACING_ENABLED: "true"
  BANKING_LAB_OTEL_SERVICE_NAME: "banking-lab-core-banking"
  BANKING_LAB_OTLP_TRACES_ENDPOINT: "http://tempo:4318/v1/traces"
  BANKING_LAB_TEMPORAL_TARGET: "temporal:7233"
  BANKING_LAB_TEMPORAL_TASK_QUEUE: "banking-case-workflows"
  BANKING_LAB_OUTBOX_BOOTSTRAP_SERVERS: "redpanda:9092"
  BANKING_LAB_OUTBOX_TOPIC: "banking.lab.domain-events"
  BANKING_LAB_SECURITY_SIMULATOR_TOKENS_ENABLED: "true"
  BANKING_LAB_SECURITY_ENABLED: "false"
  BANKING_LAB_CORS_ALLOWED_ORIGINS: "http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:3004,http://localhost:3005,http://localhost:3006,http://localhost:3007"
