apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-banking-service
  labels:
    app.kubernetes.io/name: core-banking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: core-banking-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: core-banking-service
    spec:
      containers:
        - name: core-banking-service
          image: banking-lab/core-banking-service:local
          ports:
            - containerPort: 8081
          env:
            - name: BANKING_LAB_SYNTHETIC_ONLY
              value: "true"
